# Generated by Django 2.2.28 on 2023-07-03 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Medicine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(blank=True, max_length=100, unique=True)),
                ('Type', models.CharField(blank=True, max_length=100)),
                ('Price', models.IntegerField()),
                ('Manufacturing_date', models.DateField(blank=True)),
                ('Expiry_date', models.DateField(blank=True)),
            ],
        ),
    ]
