# Generated by Django 4.2.3 on 2023-07-27 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Medicine', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicine',
            name='Expiry_date',
            field=models.DateField(),
        ),
    ]
